---

- name: include postgresql vars
  include_vars:
    file: postgres.yml

# - name: create postgresql directories

- name: install postgres packages
  apt:
    pkg: "{{ postgresql.packages }}"
    state: present
    cache_valid_time: 3600

- name: check if PGDATA dir exits
  shell: test -d /srv/postgresql/{{ postgresql_version }}/main
  register: pgdata_exists
  check_mode: no
  ignore_errors: yes
  changed_when: false

# https://wiki.debian.org/PostgreSql
- name: remove default PG cluster
  shell: /usr/bin/pg_dropcluster --stop {{ postgresql_version }} main
  check_mode: no
  ignore_errors: yes
  become: true
  become_user: postgres
  when: pgdata_exists is failed

- name: create postgresql config directory
  file:
    path: "/etc/postgresql/{{ postgresql_version }}/main/"
    state: directory
    recurse: yes
    owner: postgres
    group: postgres

- name: create new PG cluster in new location
  shell: pg_createcluster --start {{ postgresql_version }} main -D /srv/postgresql/{{ postgresql_version }}/main
  check_mode: no
  ignore_errors: yes
  when: pgdata_exists is failed

- name: deploy custom postgres conf
  template:
    src: "etc/postgresql/{{ postgresql_version }}/main/postgresql.conf.j2"
    dest: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
  notify: restart postgresql

- name: create PG super user
  postgresql_user:
    name: "{{ nominatim.conf.user }}"
    role_attr_flags: CREATEDB,CREATEROLE,SUPERUSER
  become: true
  become_user: postgres
  when: pgdata_exists is failed

