---

- name: include supervisor vars
  include_vars:
    file: supervisor.yml

- name: Install supervisor packages
  apt:
    pkg: "{{ supervisor.packages }}"
    state: latest
    cache_valid_time: 3600
  when: supervisor.packages is defined

- name: Install update-nominatim supervisor configuration
  template:
    src: etc/supervisor/conf.d/{{ item }}.j2
    dest: /etc/supervisor/conf.d/{{ item }}
  loop: "{{ supervisor.conf|flatten(levels=1) }}"
  notify: reload supervisor
