---
- name: reload apache2
  service:
    name: apache2
    state: reloaded

- name: restart postgresql
  service:
    name: postgresql
    state: restarted

- name: restart supervisor
  service:
    name: supervisor
    state: restarted
